# Generated by Django 5.0.6 on 2025-02-04 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('kelas', models.CharField(max_length=50)),
                ('tahun_masuk', models.PositiveIntegerField()),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('no_telepon_ortu', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Data Siswa',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester', models.CharField(max_length=10)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wali', to='rapor.siswa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
