# Generated by Django 5.0.6 on 2025-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='naik_kelas',
            field=models.BooleanField(default=False),
        ),
    ]
