# Generated by Django 5.0.6 on 2025-02-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0003_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapor.tahunajaran'),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.tahunajaran'),
        ),
    ]
