# Generated by Django 5.0.6 on 2025-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0004_siswa_tahun_ajaran_alter_rapor_tahun_ajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_siswa/'),
        ),
    ]
