# Generated by Django 5.0.6 on 2025-02-05 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0005_siswa_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='wali',
            name='siswa',
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('mata_pelajaran', models.ManyToManyField(related_name='guru', to='rapor.matapelajaran')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_wali', to='rapor.guru'),
        ),
        migrations.AddField(
            model_name='wali',
            name='siswa',
            field=models.ManyToManyField(related_name='wali', to='rapor.siswa'),
        ),
    ]
