# Generated by Django 5.0.6 on 2025-02-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0007_alter_guru_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='guru_foto/'),
        ),
    ]
