# Generated by Django 5.0.6 on 2025-05-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0008_guru_foto_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='naik_kelas',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='tahun_ajaran',
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='rapor',
            unique_together={('siswa', 'mata_pelajaran', 'kelas', 'semester', 'tahun_ajaran')},
        ),
        migrations.CreateModel(
            name='StatusSiswaTahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('naik', 'Naik Kelas'), ('tinggal', 'Tinggal Kelas'), ('lulus', 'Lulus'), ('keluar', 'Keluar')], default='aktif', max_length=10)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapor.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tahun_ajaran', to='rapor.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.tahunajaran')),
            ],
            options={
                'unique_together': {('siswa', 'tahun_ajaran')},
            },
        ),
    ]
