# Generated by Django 5.0.6 on 2025-05-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0009_remove_siswa_kelas_remove_siswa_naik_kelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterAktif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('aktif', models.BooleanField(default=False)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapor.tahunajaran')),
            ],
            options={
                'verbose_name': 'Semester Aktif',
                'verbose_name_plural': 'Semester Aktif',
            },
        ),
    ]
